{% set name = 'pmw' %}
{% set version = '1.3.3' %}
{% set number = '0' %}

about:
    home: http://pmw.sourceforge.net
    license: BSD
    summary: |
        Pmw is a toolkit for building high-level compound widgets, or
        megawidgets, constructed using other widgets as component
        parts. It promotes consistent look and feel within and
        between graphical applications, is highly configurable to your needs and is easy to use.



package:
    name: {{ name }}
    version: {{ version }}

build:
    number: {{ number }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://sourceforge.net/projects/pmw/files/Pmw/Pmw.{{ version }}/Pmw.{{ version }}.tar.gz

requirements:
    build:
        - tk
        - setuptools
        - python x.x
    run:
        - tk

test:
    imports:
        - Pmw
