package:
  name: yolk
  version: "0.4.3"

source:
  fn: yolk-0.4.3.tar.gz
  url: https://pypi.python.org/packages/2b/c0/73510e50668b70f3fad25328c58d7a29a300a2e452058dfdcb7c7538af7b/yolk-0.4.3.tar.gz
  md5: 10dfabca7a020058436aec9dbad70123
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - yolk = yolk:main
    #
    # Would create an entry point called yolk that calls yolk.main()

    - yolk = yolk.cli:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - yolk
    - yolk.plugins

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - yolk --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/cakebread/yolk
  license: BSD License
  summary: 'Command-line tool for querying PyPI and Python packages installed on your system.'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
