package:
  name: ws4py
  version: "0.3.5"

source:
  fn: ws4py-0.3.5.tar.gz
  url: https://pypi.python.org/packages/c8/b4/1784512791fbd196a48f282ca6c79398cace9541a9c151d89c30b6add6e1/ws4py-0.3.5.tar.gz
  md5: b0cbe30433350ef5ec98e8cbb3c3b39c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ws4py = ws4py:main
    #
    # Would create an entry point called ws4py that calls ws4py.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - ws4py
    - ws4py.client
    - ws4py.server

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/Lawouach/WebSocket-for-Python
  license: BSD License
  summary: 'WebSocket client and server library for Python 2 and 3 as well as PyPy'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
