package:
  name: parsley
  version: "1.3"

source:
  fn: Parsley-1.3.tar.gz
  url: https://pypi.python.org/packages/06/52/cac2f9e78c26cff8bb518bdb4f2b5a0c7058dec7a62087ed48fe87478ef0/Parsley-1.3.tar.gz
  sha256: 9444278d47161d5f2be76a767809a3cbe6db4db822f46a4fd7481d4057208d41

requirements:
  build:
    - python

  run:
    - python

about:
  home: http://launchpad.net/parsley
  license: MIT License
  summary: 'Parsing and pattern matching made easy.'
  license_family: MIT

