{% set name = 'django' %}
{% set version = '1.8.14' %}
{% set build = '0' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_tag: {{ version }}
  git_url: https://github.com/{{ name }}/{{ name }}.git

build:
  entry_points:
    - django-admin = django.core.management:execute_from_command_line
    - django-admin.py = django.core.management:execute_from_command_line

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - django-admin --version
  imports:
    - django
    - django.http

about:
  home: http://www.djangoproject.com/
  license: BSD
  license_file: LICENSE
  summary: Web framework that encourages rapid development
  description: |
    Django is a high-level Python Web framework that encourages rapid
    development and clean, pragmatic design. Built by experienced developers, it
    takes care of much of the hassle of Web development, so you can focus on
    writing your app without needing to reinvent the wheel.
  doc_url: https://docs.djangoproject.com/en/1.8/
  dev_url: https://github.com/{{ name }}
