package:
  name: traceback2
  version: "1.4.0"

source:
  fn: traceback2-1.4.0.tar.gz
  url: https://pypi.python.org/packages/eb/7f/e20ba11390bdfc55117c8c6070838ec914e6f0053a602390a598057884eb/traceback2-1.4.0.tar.gz
  sha256: 05acc67a09980c2ecfedd3423f7ae0104839eccb55fc645773e1caa0951c3030

requirements:
  build:
    - pbr
    - python
    - setuptools

  run:
    - python

about:
  license: Python Software Foundation License
  summary: 'Backports of the traceback module'
  license_family: Proprietary

