{% set name = "mechanicalsoup" %}
{% set version = "0.11.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/58/96/5a3b6814d4d7a079b61295d9701be0515eab25a5219257f098dca4282502/MechanicalSoup-0.11.0.tar.gz
  sha256: 2712ec0f3087cbc719c6c3dfb317a05800ff14fcdbfa67a2f9f6e07226e7a94c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - beautifulsoup4
    - lxml
    - pip
    - python
    - requests >=2.0
    - six >=1.4
  run:
    - beautifulsoup4
    - lxml
    - python
    - requests >=2.0
    - six >=1.4

test:
  imports:
    - mechanicalsoup
  #requires:
  #  - pytest
  #  - pytest-cov
  #  - pytest-flake8
  #  - pytest-httpbin
  #  - pytest-mock
  #  - requests_mock >=1.3.0

about:
  home: https://mechanicalsoup.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: 
  summary: A Python library for automating interaction with websites
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
