package:
  name: mechanicalsoup
  version: 0.8.0

source:
  url: https://files.pythonhosted.org/packages/c2/95/3bd9c99a0052e3733ca860ba675319cef129931f222b9e66cf0d27b878d5/MechanicalSoup-0.8.0.tar.gz
  sha256: 38a6ca35428196be94f87f8f036ee4a88b1418d1f77e5634ad92acfaa22c28da

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - beautifulsoup4
    - lxml
    - pip
    - python
    - requests >=2.0
    - six >=1.4
    - pytest-runner
  run:
    - beautifulsoup4
    - lxml
    - python
    - requests >=2.0
    - six >=1.4

test:
  imports:
    - mechanicalsoup

about:
  home: https://mechanicalsoup.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: 
  summary: A Python library for automating interaction with websites
  doc_url: 
  dev_url: 

